---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: spark
      version: "6.2.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: nfs-flash
