apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tunnel-credentials
    namespace: networking
data:
    credentials.json: ENC[AES256_GCM,data:sAQKClElHbCXmr9Nn1TGpnA0TGXUz3EpJLTI8vxj1XJHUJEooU/5vXpMa4zkcBpR7k5WNewNBVfO6hZfmkCxXK3yBjgeP1O6P6s5jgF8qNhLxwVGfAXvkHeHaDJbcBgDJuMhQFClOE/Dl1tkbbpq3a0z3Txdl5lrddRq3HNzZGCDRGFulhCbr85QQHW/eh4+WAWIqODC5MdsynQP+kXStBAp+4lIB3a7VrRIchqO6J7ylbzV7evfG57AHjRCf5WDJn8DnYj3s4UZc8lXJqXxjlA1DU5e1aeD,iv:jl0ohmPZ5Ks1W3bux4AbWhFP48T5PlynDatqWdmVl4w=,tag:jyRQRD7XDBp6QfWcMj8Rpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudWZaejB1Y1c3bE5RRzdK
            UFRhK0pqWllITTBOVno2MjNXWEVESlhnQjBZCndaOXpnOUswSlhuQ0dsS3ZqTE05
            b2JSNUJST1krZ3hFYlRBSklBM2g3ZXMKLS0tIHUrbEkyZ2tMbVdVWE9FQUVWYUF6
            MFMwd05OeXVERk5jcDJ6a0FITUJ5ejQKDzI6SCk2UQ6jtT3QeWuvB0iR1b+8egf7
            o0Q+ExecWVsXL2eiByBrrObV+/Npjo4faE6Ej50OVca1fwptqKDF6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T23:07:21Z"
    mac: ENC[AES256_GCM,data:rR3AsvJ8mZj6Hgm24jkogtI8y9kz/8fp9atxUnH7bkEC51Y5Ab8N3LxX9a0PxrFe+u3xZd9S3tGwxJFc/n2jfFq1VO4C2h/MJ/zCrP7jBcDLmo6aFLKWWNiFl/vJGeDBCnpq9OJUvlxOQLvejaw57h+HcV0fNc+lwp5JOklDOyo=,iv:YpwZKsZSD3mFZ0s0x6GIF8k28MFuLEDAvkbQwAVpOik=,tag:hkKL5ldz8WlZlZD4CAxe+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
