---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-dashboard
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.178.9
    ports:
      - name: webui
        port: 8006
        protocol: TCP
