---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox-dashboard
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production" # Overwrite certificate OR skip certificate
    external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
    external-dns/is-public: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "proxmox.${SECRET_DOMAIN}"
      secretName: "proxmox-dashboard-tls"
  rules:
    - host: "proxmox.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox-dashboard
                port:
                  number: 443
