---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-dashboard
  namespace: default
spec:
  ports:
    - name: webui
      port: 443
      protocol: TCP
      targetPort: 8006
  clusterIP: None
  type: ClusterIP
