apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana_password
    namespace: monitoring
data:
    grafana_password: ENC[AES256_GCM,data:i3Po2NiygoE10CYC,iv:w/mgHtdE4R5oOsdaLIt8rqVndJgQ6KJYC0h4Xt2xw2A=,tag:cnP79yB/NzK/AOXGKRhz5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVlJ5SHZSa1E3c3UyUGll
            MS9Dei85K2grSGJqMXVKa01PMUZwRE5Hb0E4CkJTNHc3Z1dINDdKdG83RVdETnBh
            Q2NsUkdGVVZ5dEhBbDdiOEk2Q2ZFazAKLS0tIERHOVVpMTU2Q1l2NmgwdkoydVZE
            VTNiK2doQnZVYnM3UzBsR3dlK0c5NHcKyga/8mp+K7XDEl5ARzxflD9ZWlnrpkga
            oPy3xitcZbRa8c3LdPPZL4eUYQsBcZd/WD6bBVR70uwAwCCo7e7Gww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T17:37:16Z"
    mac: ENC[AES256_GCM,data:Rxzhfouiott1A1zOlILKJgBFLTPlEcraUEaXkjftqAEPqn0PpNvYJsHnXa0aACL9N6o9xXeTe1pFTUkYpW4EsWW5r2iDLCNE/Y4XFlqZVIrXGtXKWNh0UBBp7CRyGaFdWyMz5aLSvhNvP9AYixSJplWON/CVc7zGqK5sc2abWp0=,iv:VtrMAJxbQEVgltUqWHZdjFOeKwsnOlqff38NbBznt+c=,tag:4h2SuiHLPP4Oxj72IIE3BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
