---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://github.com/strimzi/strimzi-kafka-operator
  - https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.31.1/strimzi-crds-0.31.1.yaml
