---
kubernetes:
  children:
    master:
      hosts:
        pi0:
          ansible_host: 192.168.178.20
        pi1:
          ansible_host: 192.168.178.21
        pi2:
          ansible_host: 192.168.178.22
    worker:
      hosts:
        pi3:
          ansible_host: 192.168.178.23
        pi4:
          ansible_host: 192.168.178.24
