# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:fcrWw2HFSUBpfmU6hIs5oaTUkUmUE5E=,iv:QRm+uEC7U+QCIQQpfpVbMtBVdn2MWyufxtVwvA8bmg4=,tag:BvwHW2pXyvU743YKaBboQw==,type:str]
    api-key: ENC[AES256_GCM,data:q2OwNEC6HvM2fIdhDHyoeWszE3wX7uMajYiLQbbWiIRY7UtZCA==,iv:6BPUPLmcx4BhtXVzrhZ5kWa2MkWeOHBgAOjpyjJQKUM=,tag:dDFJmp3z6EHQut3O5d5ffA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmZWZ2s3QU1MSFB3L0Z1
            ZUR1SzExVExyQk50QWQ2b3FEejNkT21xbFRRCllhbFlmZnhpeGNON1gwZEJtVFhF
            ZlNuSDlNaVc2a2J0emJ1djA5QmNtWWsKLS0tIDE3aFRPUmhjYno3dGFDdTVDQm1Z
            akhuU0lNcWFZTk1GMnFleGFIT3JaNHMKXqie/UdpHSAxA2aq6SVaXHK6pb2LA29U
            NcFzNFMiIKqXb//7ZLbA/QiTTS8RHsuiTehc5PaYCoPpgemWPHLUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T04:28:23Z"
    mac: ENC[AES256_GCM,data:ztc+4O11+9+jIYQdCpiwewNCUAmnA+BIkRrMhWj5h4IrjETuZW6rx7hQrDjet0FlLYsnpf9dLxRfF1CNRfAajvSmib4Ps2+fNyLGR5NGZ+DdjEnOcTLmA4QAL/IwnOmz88kk6y+WBcUm3LM97o9z/LX3I3RTwQfgNHwGqAcGZSI=,iv:z+K38ntc43eNrUo4UCNnHhzDM6JL/HmeplrPbhUa+/c=,tag:jyPZhk/URgfzhP17Dt4JVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
