# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:a4IQ0r/xFZloifRmSexd+votuPitX04=,iv:mJsSSvIRC1btSIPlLPT0K+307qzcBAzGqzBcKOUoEQM=,tag:aUUJvHBzD94hyry9s/mZHg==,type:str]
    api-key: ENC[AES256_GCM,data:Oc6J0pq2UiD0uyyYKfdfBz2ugfvWrpVcqIHuwt+MYZabZ7XZPQ==,iv:Dsfa30bO7hsbIbNW1dAXAEKxtGWiCf7SRdpWO6o+vlk=,tag:O31Qg3Xt9HT2Fr49F+LweQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNG9NRzhnZUx1TWFqeER0
            SEtad3R6QzUyR0dxL1BvS29QdzRNdm1OMm1rCm9KM0NBTFpYN05JUzc3ekU0QmlN
            YXBvZFBNQ2RZdUxyZHZxK0t4REh4cUEKLS0tIG9BbisyRk5UdzU5Vlc4aCtZZkZW
            MmtmQzQzVXVtMjVqL21Oa2FUQWRWd00K4n0TO5XaYjsbIVI9FqNivlufQDUbuMTm
            P0Op99lZw/FXkRi4fDVKlNUrYMw4u3Wf+zu0Zm9YojRTIfFnIN1q5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T19:36:43Z"
    mac: ENC[AES256_GCM,data:oXJQ9wW7EPsDBkIrqvMjmYHreaWIlliuOIQraf6/6U7OTnurKBiEwowj9s1Ab1AOSWVgkG/6X+GnwYgdeTRTDOgBZdP3ltQOClP8ArxtN/yC4IGZDFYmxWGWR8/qTD+CAbAN1Na9erQZ6Db6mf9A9OjO+bvXqdHWnlt5dnc+2OE=,iv:ghY+hD/nB1W11o8bPRraM+g1R8N6CV7l5rrtmMFynuU=,tag:ICssidy4s2AG/OaIk7EBnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
