---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  install:
    createNamespace: true       # just to be sure
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
