---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  install:
    createNamespace: true       # just to be sure
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # https://github.com/elastic/cloud-on-k8s/blob/2.3/deploy/eck-operator/values.yaml
    installCRDs: false
    fullnameOverride: "elastic-operator"
    nodeSelector:
      kubernetes.io/arch: amd64
