kind: Secret
ansible_user: ENC[AES256_GCM,data:CGQ=,iv:oU0EDN17JJ4FATgEmTDbVCfPGFZvi13EtsK6a8yaQcI=,tag:UQ8Jyk3m60yGCE77ibzNlg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:is/wi6u1,iv:rs+QqjSmmmw7uWt0bxbAzrbfcCU7ppjLSr2tfK5zq4g=,tag:zlRFb0QkJgUkyGGHVkmjDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQjhRazVzKzZlZU9xVzFV
            SnQvcVkyY0NBaGZ4aUpTNXA5S3Y4VWt5bHdrCngxaHJCcUcwMDU4SGwzYXd1SVln
            TmtyMGgyWVRoMXlxREN1L1I4NGpVUUUKLS0tIFAzVXFCVDQxQk9zdHNscW0rcG54
            ZW5qMEVJMTQ0OEtuZDMzUEtDWDFOK00KwlCPyFs4BMgEmauvvequgZPzJq1Yvkyr
            EXx1LbAKqoA4ntDGoLv917555SYddbV+6XdK6wHaxvEkddhKvUDYNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T04:28:23Z"
    mac: ENC[AES256_GCM,data:3AfyTRIiD5GhlGo0ygwfWxnZPVeb2sdzPCSZMRJP0ZsFZwTui+BhcNlDkuvCR92sm75chlQ5oui/pwso3QHUIYF//Y/Sq6EGBDnQtV1DkJ5aqPVHAEIgQ9dYNu0qbf/K0Zs8YHRZbkPKvjlEd7tcDTzNtFxisCfBfgV4YCbcq1o=,iv:pcMiwZU9O0CUF8ga55VLBxHJ82ZNF7pJq2K5CS5DSBk=,tag:iUFtz+pgBcxyf53nhQYSzw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
