kind: Secret
ansible_user: ENC[AES256_GCM,data:NsI=,iv:zlKBRPVwYauiMknCMdIIFIv3vKAz+vcnPd0VrzlfVbk=,tag:fWtnRytGlIKHI4w8auEhdQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:A2TTc1zu,iv:Bkmlj7ipMrEiff4dEM0B1HAa5KaSjT4CJ6jCIPdIJ7c=,tag:42LZKUjPApdgIKLbh8+G6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGo4RHExQXdWZWIxek5o
            a2lVYkZncWJLKzRyekdZdkRRSjBQVVpuTkI4Ckc1ZVl4ZkJibHlrL3Q1M3E3OTcz
            OGM3a0JLdGMrdW82clM5WFExdFZiQ1UKLS0tIGlFYXo2SzZnemx1dWE0eExxYzBr
            anVRbjdRYkloMGNMZzdSMVFpaWlaYUEKeIR9rXxmS3z67k3FvuZNyNQoqnMrTcnN
            teZlxgH+f/Do0KcOV1R3BehdHbeReACFsdKzo2vPnTsoBoOassnitw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T19:36:43Z"
    mac: ENC[AES256_GCM,data:AWIPtVL2WXaXJT5Yg/ETGUXaakcPPaUJ52X1whFwfAv3o34koQsbi5+QhgyO+Fzp02Zp/09vK/iR+5P8+6Kb+0/+xf7ehJVxgxgaIOyzzsxPFuKfCviwW5wQW+EBsFgVlu/OVnj/fQEZh3FfvoJfrTnXrHhdjpxTV+0cp7CORUA=,iv:fJiWYIhaXWxCXqn4hZgn6MeH5kdWc+G2D4Irk0XOL84=,tag:cxlMMpP9yo4Cw+mVxvw79Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
