---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeName: pi0
      volumes:
        - name: ha-storage          # nfs path for ha configuration
          persistentVolumeClaim:
            claimName: home-assistant-claim
        - name: ha-mysql-storage    # local path for mysql storage
          hostPath:
            path: /opt/ha-mysql
            type: DirectoryOrCreate
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          name: home-assistant
          volumeMounts:
            - mountPath: "/config"
              name: ha-storage
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-recorder-pass
                  key: password
          volumeMounts:
            - name: ha-mysql-storage
              mountPath: /var/lib/mysql
