---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esphome
  name: esphome
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      # hostNetwork: true
      nodeName: pi0
      volumes:
        - name: esphome-storage          # nfs path for ha configuration
          persistentVolumeClaim:
            claimName: esphome-claim
      containers:
        - image: esphome/esphome:2023.2.4
          name: esphome
          env:
            - name: ESPHOME_DASHBOARD_USE_PING
              value: "true"
            - name: ESPHOME_DASHBOARD_RELATIVE_URL
              value: "/"
          volumeMounts:
            - mountPath: "/config"
              name: esphome-storage
