---
apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: homeassistant
spec:
  selector:
    app: esphome
  ports:
    - protocol: TCP
      port: 6052
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esphome-ingress
  namespace: homeassistant
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production" # Overwrite certificate OR skip certificate
    # external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
    # external-dns/is-public: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "esphome.${SECRET_DOMAIN}"
      secretName: "esphome-tls"
  rules:
    - host: esphome.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: esphome
                port:
                  number: 6052
