kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: homeassistant
  name: home-assistant-claim
  namespace: homeassistant
spec:
  storageClassName: nfs-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
