apiVersion: v1
kind: Secret
metadata:
    name: mysql-recorder-pass
    namespace: homeassistant
type: Opaque
data:
    password: ENC[AES256_GCM,data:dgRk9bh+3PPuFg0ms3b9OQ==,iv:EfyMsy3LU2Wa7Tzc9bFcgMqaOU9TlHkepIHkrDcRgr4=,tag:tTbdQ8qidhfkrnq5rpkKTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3NaVUoxb052eHVDVDQ1
            VjBNdlAvSnRlVmllbzhBay9PU0tReHhYYkZBCmZDbjdmdEorNnJCYjN3KzBMZXdS
            ZE82eDk2dTV2anQ1QmFJU2VqUDIwaGcKLS0tIEVoR2hYYUNLVy9LeWJ3NnNocGUw
            SWRuZnd4S25QYUs3WTVsdUlJL3VEeW8KhuX0O+zmowkTbF+0ZkFCI7pMxABwY4wz
            kS3U7Vs3jvvS0SuljvNDQPw61+Uf7p5JgniHfkWm2xdpMbAPmz8rdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-11T18:50:44Z"
    mac: ENC[AES256_GCM,data:LyY//to1P6N39fY1P7Fze8yeYr0RWceoUCujaIAn/PKEHg4EWaofnCqtLefFW+pmu5GyJgcXp7MyrfJtF3sKifI891hF50kgTpt/D30TkLFd+yNZ8m3/ShIaO7+1CIc42Z1P/GGFkmq3/umHkfsjAP+duXn+80ZyUfOBoerHxfg=,iv:iMCPCbOm4Nk5C1RfqLYkOyX3SUqF76SpwuT4RJ9mq/o=,tag:0GsGv1f1RARnFJbceRey/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
