---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator-crds
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator-crds
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
