---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://helm.elastic.co chart=eck-operator-crds
  - https://download.elastic.co/downloads/eck/2.3.0/crds.yaml
