---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cluster-lets-encrypt
  namespace: strimzi
spec:
  secretName: my-cluster-lets-encrypt
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizations:
      - my-org
  dnsNames:
    - bootstrap-kafka.teamkhunglong.com
