---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: strimzi
  labels:
    app: my-cluster
spec:
  kafka:
    version: 3.2.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          class: "traefik"
          bootstrap:
            annotations:
              # external-dns.alpha.kubernetes.io/hostname: bootstrap-kafka.teamkhunglong.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
              external-dns/is-public: "true"
              external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              # traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
              traefik.ingress.kubernetes.io/router.tls: "false"
            host: bootstrap-kafka.teamkhunglong.com
          brokers:
            - broker: 0
              annotations:
                # external-dns.alpha.kubernetes.io/hostname: broker-0.teamkhunglong.com.
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns/is-public: "true"
                external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
                traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
              host: broker-0.teamkhunglong.com
            - broker: 1
              annotations:
                # external-dns.alpha.kubernetes.io/hostname: broker-1.teamkhunglong.com.
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns/is-public: "true"
                external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
                traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
              host: broker-1.teamkhunglong.com
            - broker: 2
              annotations:
                # external-dns.alpha.kubernetes.io/hostname: broker-2.teamkhunglong.com.
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns/is-public: "true"
                external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
                traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
              host: broker-2.teamkhunglong.com
          brokerCertChainAndKey:
            secretName: my-cluster-lets-encrypt
            certificate: tls.crt
            key: tls.key
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
