---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: strimzi
  labels:
    app: my-cluster
spec:
  cruiseControl:
    image: ghcr.io/minhtt159/cruise-control-ui:kafka-3.3.2-ccfe-0.4.0
    config:
      webserver.security.enable: false
  kafka:
    version: 3.3.2
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          # class: "traefik"
          bootstrap:
            loadBalancerIP: "192.168.178.52"
            # annotations:
            # metallb.universe.tf/loadBalancerIPs:
            #   - "192.168.178.52"
            # external-dns.alpha.kubernetes.io/hostname: bootstrap-kafka.teamkhunglong.com.
            # external-dns.alpha.kubernetes.io/ttl: "60"
            # external-dns/is-public: "true"
            # external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
            # alternativeNames:
            #   - bootstrap-kafka.teamkhunglong.com
          brokers:
            - broker: 0
              loadBalancerIP: "192.168.178.54"
            - broker: 1
              loadBalancerIP: "192.168.178.55"
            - broker: 2
              loadBalancerIP: "192.168.178.56"
          # brokerCertChainAndKey:
          #   secretName: my-cluster-lets-encrypt
          #   certificate: tls.crt
          #   key: tls.key
      # - name: e0tls
      #   port: 9095
      #   type: loadbalancer
      #   tls: false
      #   configuration:
      #     bootstrap:
      #       # alternativeNames:
      #       #   - bootstrap-kafka.teamkhunglong.com
      #       loadBalancerIP: "192.168.178.53"
      #     brokers:
      #       - broker: 0
      #         loadBalancerIP: "192.168.178.57"
      #       - broker: 1
      #         loadBalancerIP: "192.168.178.58"
      #       - broker: 2
      #         loadBalancerIP: "192.168.178.59"
    # authorization:
    #   type: "simple"
    #   superUsers:
    #     - CN=my-user
    #     - minhtt159
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
