apiVersion: v1
kind: Secret
metadata:
    name: my-connect-secret-kafka
type: Opaque
data:
    my-password-field-kafka: ENC[AES256_GCM,data:zalKWk5LVjoJpaYir+xHHQ==,iv:i6Dpf7+hJggF4da5KlP4TYyEW98NOLygxbWjlqqN6MM=,tag:hpBJyATXI6n1Ps5YpyvRng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSGNXY0tXNHE5VDJyODVt
            eUQ4OGFreS9acjhJVld4QWVBNEtaZVJNUDNZCi9FaGxvSjRuS1FmcG9IbHZ1alFu
            WE1zcXNaZStYbW9zTmdyYnJtWDNCcnMKLS0tIHc4Qy9QTXhIQ1VtZ2hNNVkrdzR0
            dkFILzgyam5aajJNNHlGRGN1MXVuS1kKfsq4OBKcKsZ+y7qM/wB81sDqDZ7DvDB+
            Z/VT8+Wuv6tr/53CunibcmXRnL4GEf2ni+hTTkvfDGS8ImzLVXo+LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T10:37:11Z"
    mac: ENC[AES256_GCM,data:Q8z4MafHycxK5OPeuLZQIa8/Q9K7tDW3CVworV8H/QmW1WDTqKrUBM/FEAEqcfnv7IEuA5qju5bqI2eKChkcGC0aOQMbMYloeCcWOQgKD5GISTDAs2OtXs1XGUtnj4RWUi/hl8WS+Wrtei6B3zqtu7l3JD/4NkC+uPvopn6Aolw=,iv:SbIHj0MLqsPoGTkavZJdp9n4w/vHbIF7EqfzJJj8fBM=,tag:r/8HytvVlg98gxeQ+XsHSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
