apiVersion: v1
kind: Secret
metadata:
    name: my-connect-secret-kafka
    namespace: strimzi
type: Opaque
data:
    my-password-field-kafka: ENC[AES256_GCM,data:zalKWk5LVjoJpaYir+xHHQ==,iv:i6Dpf7+hJggF4da5KlP4TYyEW98NOLygxbWjlqqN6MM=,tag:hpBJyATXI6n1Ps5YpyvRng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSGNXY0tXNHE5VDJyODVt
            eUQ4OGFreS9acjhJVld4QWVBNEtaZVJNUDNZCi9FaGxvSjRuS1FmcG9IbHZ1alFu
            WE1zcXNaZStYbW9zTmdyYnJtWDNCcnMKLS0tIHc4Qy9QTXhIQ1VtZ2hNNVkrdzR0
            dkFILzgyam5aajJNNHlGRGN1MXVuS1kKfsq4OBKcKsZ+y7qM/wB81sDqDZ7DvDB+
            Z/VT8+Wuv6tr/53CunibcmXRnL4GEf2ni+hTTkvfDGS8ImzLVXo+LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T10:48:22Z"
    mac: ENC[AES256_GCM,data:xg2bWc5Q91M8gqon/KHP/q4858fQa4XUTOigpH3d/82JZcyNlwF8N8QGjp2x4b+XY7szFxEqm1xN8DEUru1OV6RwqFZYdL6e4WYi4uzxGM/8l9IDHcWJjUZ1J4jM/YKIib6zoopISxIbb2GaMwFlgi02tfincXRK7749OFPShJc=,iv:1DqRg+7y7hngl1qAZDGzltJcghppIwt/42KiAeiCq08=,tag:A+KFTb+/xU1PLbMgCDm6ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
