# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YD+vhdvusa7zoKnToCha5JxDC8unEWCo1lLSl4syT73SgoMCYA==,iv:+iORR3qEj2yn6MQc/M1fyF7iVCEaHZTcHZ0Tm5xdKNk=,tag:o237JVvTiwqLvjTObZmxYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbWw0R21IdjJNcXlTK3gw
            T0tIdnp3MGROWGRFVXpPbUdMRVhHUElxYkUwCk01OUl6Z3Zsamd6VnVuQlVuNEtF
            WkIvVERwRWcxMXJScG5jR3paZUxYTkkKLS0tIFd3dHpPUjBJNVp5bDViNUEwcUh0
            UytvSjdzUThWaTJJOUUyZHZFendTd0UKFlfNuOMUpIIVbiwgxCoF4shhsCoLL8or
            kBCD4E3xLMIwYJcQ19CsYlkhq8l6tSqurtHmYy1riaNFxkBLIzLMkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T19:36:43Z"
    mac: ENC[AES256_GCM,data:H+Oruu7OrycUliNGLECG7974dWLu0H08u13G1OVS8bp5Inp81X4tBvKrM7nw+qCNcC/lMV0IoxJWS1bwzpIqiDYciRqm8h54c5IVCXw/tE3dEP6oCCzMT7lI/EZxT1p+Mw+kOnvV4O7AbFFcOkM2IRksDuGXOMOUbyajcCxy34o=,iv:2p1yMfLIo7jfQTwHgr61sreOgBN7TucHAKbxDiB7aLw=,tag:EO1kfuLYbggE2m/IYEJw8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
