# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:6JVIRg2/fQ4LUDAVT0MKiixkRTqa+9cEiJEn24STkVwE21J0hQ==,iv:irRjdP9XjOBjefhDmjNGaqPrZ0LlMhwCre+GAT+M/ng=,tag:m8Dr2yNCIZvSHV7xOtXz1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRjBSbGNyTDJzSnhxeC9L
            TkJyK1pVcVl3aEpGODAxeUUrNU1vNmoydFJVCkkvN2lNOUxxTTlYSUJpckh3TW90
            d0EyeW96aHZRYzZNb3hhUDBnajY4MTQKLS0tIGV3MXZPNGtMUWM5U2NuUGxwSjNt
            cGpqZ3BKZzJzRHFEQUJHSGIyeGt4akUKA3xLi8IFLN9VWLE3hsUw/X7caybO7SxG
            h9QKtsnNn2DnecGGPRycb3ZGhtNEXdOmU5QSKKFoZqkMTR9zOhmo3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T18:09:14Z"
    mac: ENC[AES256_GCM,data:wIGLjIi3/TtFQih1Qf4E2YLByBuBnDev34cd2WL9bAKLrjlRCc53MVdUGWQQ3Hc3X+E3wIBII5UrpDzDDZK+C3xPZCMtVThGEFF9wh8rcmmboJjBkcWEsax9xOx7MCsI+Mgp/rtFYW60JVuM72zP9zu43hhN0xEfwLLJORCNh7U=,iv:l7nbNAKkMtE4oAmPiSsfzaCxZHbi5Vv3kiHpWhW9m5I=,tag:JH5hro/rP+lSjKmIjfDI9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
