# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:CY1Z0KbJrXKVNEn5fWBqz2oCR/X5q4Yve1QZKrw51+ta8w1/Ag==,iv:fuG+oKIuuqLOpc62U9QtPQmwN7OtdmpXVWoezuQxcGE=,tag:1g5dAT8B+5Qjr6C+OlzlEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fp9jehs9sjfl50edpdqsf5vzuua8hxvg7n4xk79enpeflwa5jf4steepf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR2N0ZkxqcGdRT01WZFJ0
            NHpBeGFhUWJCZ0hyVzNMQ3JrWSsyU2JNR0ZrCjQ1alpBS3EvN214YVhXVDRzNWhF
            RTlFWlU0NlZaUVBSenJtK1JsVzdiZ2cKLS0tIGoxOExka2UyT1VFaFRXT1g2WURv
            T000WEYxSm84UXhYaW0wTHcvdC95SVEKk7V+Tw16kuLZhUP16jIBOf5a0wDE+Lxs
            2kR1QupjX8KwaUnGeCN6wIDBtFGlM6oDORO0/Ylkdl+oeMMfAwrC5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T04:28:23Z"
    mac: ENC[AES256_GCM,data:7ohomG3EszVXa/0QNlCzgkqejeNpKwdUz0inkllsWEMIwNallCIP7nQ9ho3xaeAGFEJBIujWhUiARwK0hpyNraBlNWkp2qT79EqRnzrVMtQtLwNKNIzDzhBs1/RrmtZysDz+EYd+ZGse94mmnCQaaKaCKVnQF7r46Ckp9u2+XoM=,iv:zquXg4bryfFUV0vRUqCb9nvbinUSWiuDIXbL4yuUP3s=,tag:uuAU/sQVdDNYK7j73o6NXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
