---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: strimzi
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.33.1"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true       # just to be sure
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/values.yaml
    logLevel: INFO
