---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-flash
  namespace: nfs-provision
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local/nfs-flash # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "true"
