---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hajimari:
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - networking
          - monitoring
          - strimzi
      name: "Minh"
      title: Hajimari
      lightTheme: gazette
      darkTheme: horizon
      customThemes:
        - name: danger
          backgroundColor: '#0c0e0c'
          primaryColor: '#eaebea'
          accentColor: '#d8323c'
      showGreeting: true
      showAppGroups: false
      showAppUrls: true
      showAppInfo: false
      showAppStatus: true
      defaultAppIcon: mdi:application
      showBookmarkGroups: true
      showGlobalBookmarks: false
      alwaysTargetBlank: false
      defaultSearchProvider: Google
      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: 'y'
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
      customApps: []
      # groups:
      #   - name: Communicate
      #     links:
      #       - name: Discord
      #         url: "https://discord.com"
      #       - name: Gmail
      #         url: "https://gmail.com"
      #       - name: Slack
      #         url: "https://slack.com/signin"
      #   - name: Cloud
      #     links:
      #       - name: Box
      #         url: "https://box.com"
      #       - name: Dropbox
      #         url: "https://dropbox.com"
      #       - name: Drive
      #         url: "https://drive.google.com"
      #   - name: Design
      #     links:
      #       - name: Awwwards
      #         url: "https://awwwards.com"
      #       - name: Dribbble
      #         url: "https://dribbble.com"
      #       - name: Muz.li
      #         url: "https://medium.muz.li/"
      #   - name: Dev
      #     links:
      #       - name: Codepen
      #         url: "https://codepen.io/"
      #       - name: Devdocs
      #         url: "https://devdocs.io"
      #       - name: Devhints
      #         url: "https://devhints.io"
      #   - name: Lifestyle
      #     links:
      #       - name: Design Milk
      #         url: "https://design-milk.com/category/interior-design/"
      #       - name: Dwell
      #         url: "https://www.dwell.com/"
      #       - name: Freshome
      #         url: "https://www.mymove.com/freshome/"
      #   - name: Media
      #     links:
      #       - name: Spotify
      #         url: "http://browse.spotify.com"
      #       - name: Trakt
      #         url: "http://trakt.tv"
      #       - name: YouTube
      #         url: "https://youtube.com/feed/subscriptions"
      #   - name: Reading
      #     links:
      #       - name: Instapaper
      #         url: "https://www.instapaper.com/u"
      #       - name: Medium
      #         url: "http://medium.com"
      #       - name: Reddit
      #         url: "http://reddit.com"
      #   - name: Tech
      #     links:
      #       - name: Hacker News
      #         url: "https://news.ycombinator.com/"
      #       - name: The Verge
      #         url: "https://theverge.com/"
      #       - name: MIT Technology Review
      #         url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNELID}.cfargotunnel.com"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    # TODO: what is this?
    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
